### ISSUE TITLE
安装插件后mcl启动报错

### ISSUE THREAD

**Issue by EsunR** [iTXTech/soyuz#2]
mcl-installer 版本： mcl-installer-1.0.6-linux-aarch64-musl

安装插件后出现报错信息：`2022-05-15 16:50:47 E/MCL Addon: java.lang.NoSuchMethodError: 'net.mamoe.mirai.console.MiraiConsoleImplementation net.mamoe.mirai.console.MiraiConsoleImplementation.getOrigin()'`

具体的控制台输出如下：

```
16:50:34 [INFO] iTXTech Mirai Console Loader version 2.0.1-b5303b5
  16:50:34 [INFO] https://github.com/iTXTech/mirai-console-loader
  16:50:34 [INFO] This program is licensed under GNU AGPL v3
  16:50:39 [INFO] Mirai Console Loader Announcement:
Mirai Console Loader 公告栏

如果在图片上传的时候遇到问题请与我们联系 (需要提供图片文件源本)
`- 如 Unsupported image type for ExternalResource *
`  considering use gif/png/bmp/jpg format.
`- Tracker: https://github.com/mamoe/mirai/issues/new/choose

常用资源整合
`- https://mirai.mamoe.net/topic/653
 
如果无法获取Mirai-Repo信息, 例如启动时出现JSON解析错误
请升级到MCL 2.0 Beta并将 config.json 中的 Mirai-Repo 更改为 https://repo.itxtech.org

  16:50:39 [INFO] Verifying "net.mamoe:mirai-console" v2.10.3
  16:50:39 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.10.3
  16:50:39 [INFO] Verifying "net.mamoe:mirai-core-all" v2.10.3
  16:50:40 [INFO] Verifying "org.itxtech:mcl-addon" v2.0.2
  16:50:40 [INFO] Verifying "org.itxtech:soyuz"
  16:50:40 [INFO] Updating "org.itxtech:soyuz" to v1.0.0
 Downloading soyuz-1.0.0.jar [==============================] 1.32 MB                         
 Downloading soyuz-1.0.0.sha1 [==============================] 40 B                    
2022-05-15 16:50:44 I/main: Starting mirai-console...
2022-05-15 16:50:45 I/main: Backend: version 2.10.3, built on 2022-05-08 17:33:45.
2022-05-15 16:50:45 I/main: Frontend Terminal: version 2.10.3, provided by Mamoe Technologies
2022-05-15 16:50:45 I/main: Welcome to visit https://mirai.mamoe.net/
2022-05-15 16:50:45 I/plugin: Successfully loaded plugin MCL Addon v2.0.2
2022-05-15 16:50:45 I/plugin: Successfully loaded plugin Soyuz v1.0.0
2022-05-15 16:50:46 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2022-05-15 16:50:46 I/MCL Addon: iTXTech MCL Version: 2.0.1-b5303b5
2022-05-15 16:50:47 E/MCL Addon: java.lang.NoSuchMethodError: 'net.mamoe.mirai.console.MiraiConsoleImplementation net.mamoe.mirai.console.MiraiConsoleImplementation.getOrigin()'
java.lang.NoSuchMethodError: 'net.mamoe.mirai.console.MiraiConsoleImplementation net.mamoe.mirai.console.MiraiConsoleImplementation.getOrigin()'
        at org.itxtech.soyuz.handler.builtin.PushLogHandler.<init>(PushLogHandler.kt:58)
        at org.itxtech.soyuz.handler.HandlerManager.<clinit>(handler.kt:44)
        at org.itxtech.mcl.addon.Addon.<init>(Addon.kt:51)
        at org.itxtech.mcl.addon.PluginMain.onEnable(PluginMain.kt:47)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:117)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:164)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:36)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:47)
        at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:135)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:177)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:202)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:401)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:156)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:155)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:47)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:89)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:79)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:101)
        at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:109)
        at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:148)
        at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:189)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:146)
        at org.itxtech.mcl.Loader.start(Loader.java:189)
        at org.itxtech.mcl.Loader.main(Loader.java:79)

2022-05-15 16:50:47 I/Soyuz: Soyuz Access Token: HpOppGzo8Ho8RomxjNGh
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
2022-05-15 16:50:47 I/Soyuz: iTXTech Soyuz is listening on ws://localhost:9876
2022-05-15 16:50:47 I/main: 2 plugin(s) enabled.
2022-05-15 16:50:47 I/main: mirai-console started successfully.
```

**Comment by PeratX** [comment]
soyuz至少需要mirai 2.11
